services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev  
    container_name: angular-dev
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules